### PR TITLE
Fix magic detection for HTML with `<svg`

### LINKED ISSUE #67: image/svg+xml returned for an html document with svg in it
### Summary

A properly declared HTML document that contains some svg is being detected as `image/svg+xml`. No hints given to Marcel seem to affect this result.

### Reproduction:

```
Marcel::MimeType.for(
  StringIO.new('<!doctype html><html><body><svg></svg></body></html>'), 
  name: 'index.html', 
  declared_type: 'text/html',
)
=> 'image/svg+xml
```

### What I expect to happen:

Returns `text/html`

### What actually happens:

Returns `image/svg+xml`.

From what I could gather, the `image/svg+xml` matcher is position 22 in the Magic types and `text/html` is position 361. SVG's magic range is ... large, so it pretty much always wins and believes the magic bytes to prove the type.

What's the ideal solution here?

### PR DESCRIPTION
**Pull request by ursm**
Fixed a problem in which HTML files containing `<svg` were misidentified as SVG.

At first glance, this problem appears to be solved by adjusting the value of the priority attribute in custom.xml. However, due to the special treatment of common_types in script/generate_tables.rb, it was actually necessary to rearrange common_types itself.

Fixes #67

### CODE REVIEW

File: lib/marcel/tables.rb [hunk 1]
```diff
@@ -2411,7 +2412,7 @@ module Marcel
     ['video/x-flv', [[0, b['FLV']]]],
     ['audio/mpeg', [[0, b["\377\362"]], [0, b["\377\363"]], [0, b["\377\364"]], [0, b["\377\365"]], [0, b["\377\366"]], [0, b["\377\367"]], [0, b["\377\372"]], [0, b["\377\373"]], [0, b["\377\374"]], [0, b["\377\375"]], [0, b["\377\377"]], [0, b['ID3']]]],
     ['application/pdf', [[0, b['%PDF-']], [0, b["\357\273\277%PDF-"]]]],
-    ['application/msword', [[0..8, b["\320\317\021\340\241\261\032\341"], [[546, b['jbjb']], [546, b['bjbj']]]]]],
+    ['application/msword', [[2080, b['Microsoft Word 6.0 Document']], [2080, b['Documento Microsoft Word 6']], [2112, b['MSWordDoc']], [0, b["1\276\000\000"]], [0, b['PO^Q`']], [0, b["\3767\000#"]], [0, b["\333\245-\000\000\000"]], [0, b["\224\246."]], [0..8, b["\320\317\021\340\241\261\032\341"], [[1152..4096, b["W\000o\000r\000d\000D\000o\000c\000u\000m\000e\000n\000t"]]]]]],
```
Comment (ursm) [inline lib/marcel/tables.rb:2415]: These lines appear to have been replaced with L2502-L2503. I have no idea why this is happening.

**Comment by tricknotes** [comment]
@rafaelfranca 
Could you release a new version?
I want to use this change as a released version.

**Comment by jeremy** [comment]
Note this PR modifies the autogenerated tables directly. It'll be overwritten the next time Tika data is updated.

I'll see whether I can fix it but will revert otherwise.
